import * as THREE from 'three';
import { buildChunk, chunkIndices, cubeToSphere } from './terrain-builder.js';
import { runTask } from './terrain-worker.js';

/**
 * Quadtree LOD over the six faces of a cube-sphere planet.
 *
 * A node is split only when all four children have finished building, so the
 * displayed set never has holes or overlaps; skirts hide the cracks between
 * neighbouring levels. Chunk vertex data is generated by a small worker pool
 * (falling back to a time-budgeted main-thread queue).
 */

export class TerrainWorkerPool {
  constructor(specs, { size = Math.max(1, Math.min(3, (navigator.hardwareConcurrency || 4) - 1)), shapes = null } = {}) {
    this.queue = [];
    this.nextId = 1;
    this.workers = [];
    this.shapes = shapes;
    this.floraContexts = new Map();
    this.stats = { built: 0, mainThread: 0 };
    try {
      for (let i = 0; i < size; i++) {
        const worker = new Worker(new URL('./terrain-worker.js', import.meta.url), { type: 'module' });
        const slot = { worker, inflight: new Map(), ready: false, failed: false };
        worker.onmessage = event => this.#onMessage(slot, event.data);
        worker.onerror = () => this.#fail(slot);
        worker.postMessage({ type: 'init', specs });
        this.workers.push(slot);
      }
    } catch {
      this.workers = [];
    }
  }
  #onMessage(slot, message) {
    if (message.type === 'ready') { slot.ready = true; this.pump(); return; }
    const ticket = slot.inflight.get(message.id);
    slot.inflight.delete(message.id);
    if (message.type === 'result') { this.stats.built++; ticket?.callback(message.result); }
    else if (message.type === 'error') { console.warn('world worker:', message.error); ticket?.callback(null); }
    this.pump();
  }
  /** A crashed worker hands its unfinished tasks back to the queue (another worker or the main thread takes them). */
  #fail(slot) {
    if (slot.failed) return;
    slot.failed = true;
    slot.worker.terminate();
    this.queue.push(...slot.inflight.values());
    slot.inflight.clear();
    this.pump();
  }
  /** Shares per-planet flora context with every worker (and the fallback). */
  setFloraContext(planet, ctx) {
    this.floraContexts.set(planet, ctx);
    for (const slot of this.workers) slot.worker.postMessage({ type: 'floraInit', planet, ctx });
  }
  /** Queue a task ({type:'build'|'flora', planet, ...}). Returns a cancellable ticket. */
  request(task, priority, callback) {
    const ticket = { id: this.nextId++, task, priority, callback, cancelled: false };
    this.queue.push(ticket);
    return ticket;
  }
  cancel(ticket) { if (ticket) ticket.cancelled = true; }
  get usable() { return this.workers.some(w => !w.failed); }
  pump(mainThreadBudgetMs = 0) {
    if (!this.queue.length) return;
    this.queue = this.queue.filter(t => !t.cancelled);
    this.queue.sort((a, b) => a.priority - b.priority);
    const live = this.workers.filter(w => w.ready && !w.failed);
    for (const slot of live) {
      while (slot.inflight.size < 2 && this.queue.length) {
        const ticket = this.queue.shift();
        slot.inflight.set(ticket.id, ticket);
        slot.worker.postMessage({ type: 'task', id: ticket.id, task: ticket.task });
      }
    }
    // No working workers: run tasks synchronously within a frame budget.
    if (!this.usable && this.shapes && mainThreadBudgetMs > 0) {
      const start = performance.now();
      while (this.queue.length && performance.now() - start < mainThreadBudgetMs) {
        const ticket = this.queue.shift();
        const result = runTask(ticket.task, id => this.shapes.get(id), id => this.floraContexts.get(id));
        this.stats.mainThread++;
        ticket.callback(result);
      }
    }
  }
  dispose() { for (const w of this.workers) w.worker.terminate(); this.workers = []; this.queue = []; }
}

let sharedIndex = null;
function indexAttribute(N) {
  if (!sharedIndex || sharedIndex.N !== N) sharedIndex = { N, attribute: new THREE.BufferAttribute(chunkIndices(N), 1) };
  return sharedIndex.attribute;
}

export class PlanetTerrain {
  /**
   * @param {object} o
   * @param {object} o.spec planet spec (system.js)
   * @param {object} o.shape createPlanetShape(spec)
   * @param {THREE.Material} o.material terrain material
   * @param {TerrainWorkerPool} o.pool worker pool
   */
  constructor({ spec, shape, material, pool, N = 32, splitK = 1.45, maxChunkSize = 56 }) {
    this.spec = spec; this.shape = shape; this.material = material; this.pool = pool; this.N = N; this.splitK = splitK;
    this.center = new THREE.Vector3(...spec.position);
    this.group = new THREE.Group(); this.group.name = `${spec.id}-terrain`;
    this.group.position.copy(this.center); this.group.updateMatrixWorld();
    this.maxLevel = Math.max(2, Math.ceil(Math.log2(spec.radius * Math.PI / 2 / maxChunkSize)));
    this.frame = 0;
    this.shown = new Set();
    this.ready = new Set();
    this.stats = { visible: 0, triangles: 0, pending: 0, cached: 0 };
    this.detail = 1;
    this.roots = [];
    for (let face = 0; face < 6; face++) {
      const root = this.#node(face, 0, 0, 0);
      this.#attach(root, buildChunk(shape, { face, level: 0, ix: 0, iy: 0, N }));
      this.roots.push(root);
    }
    this.camLocal = new THREE.Vector3();
    // Conservative occluder for horizon culling: nothing renders below it.
    this.occluderRadius = spec.radius + (shape.seaLevel !== null ? shape.seaLevel : -60) - 4;
    this._q = new THREE.Vector3();
  }
  /**
   * Horizon culling (after Cesium's ellipsoidal occluder test, specialised to a
   * sphere). Tests the highest point of the node's bounding sphere: if even
   * that is hidden behind the planet's curvature, the whole chunk is.
   */
  #occluded(node, cam) {
    const Ro = this.occluderRadius, pc = cam.clone().divideScalar(Ro);
    const vh2 = pc.lengthSq() - 1;
    if (vh2 <= 0) return false;
    const top = this._q.copy(node.center).normalize().multiplyScalar(node.center.length() + node.bound).divideScalar(Ro);
    const vt = top.sub(pc), vtDotVc = -vt.dot(pc);
    return vtDotVc > vh2 && (vtDotVc * vtDotVc) / vt.lengthSq() > vh2;
  }
  #node(face, level, ix, iy) {
    const size = 2 / (1 << level), dir = cubeToSphere(face, -1 + (ix + 0.5) * size, -1 + (iy + 0.5) * size);
    const arc = this.spec.radius * (Math.PI / 2) / (1 << level);
    return { face, level, ix, iy, key: `${face}/${level}/${ix}/${iy}`, arc, children: null, mesh: null, state: 'none', ticket: null, touched: 0,
      center: new THREE.Vector3(dir[0], dir[1], dir[2]).multiplyScalar(this.spec.radius), bound: arc * 0.75 + 200 };
  }
  #attach(node, chunk) {
    if (!chunk) { node.state = 'none'; return; }
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.BufferAttribute(chunk.positions, 3));
    geometry.setAttribute('normal', new THREE.BufferAttribute(chunk.normals, 3));
    geometry.setAttribute('color', new THREE.BufferAttribute(chunk.colors, 3));
    geometry.setAttribute('aux', new THREE.BufferAttribute(chunk.aux, 2));
    geometry.setIndex(indexAttribute(this.N));
    geometry.boundingSphere = new THREE.Sphere(new THREE.Vector3(), chunk.bound);
    const mesh = new THREE.Mesh(geometry, this.material);
    mesh.position.fromArray(chunk.origin);
    mesh.matrixAutoUpdate = false; mesh.updateMatrix();
    mesh.receiveShadow = true; mesh.castShadow = false;
    mesh.visible = false; mesh.name = `chunk ${node.key}`;
    mesh.userData.terrain = this;
    this.group.add(mesh);
    node.mesh = mesh; node.state = 'ready';
    node.center.fromArray(chunk.origin).multiplyScalar((chunk.minR + chunk.maxR) / 2 / this.spec.radius);
    node.bound = chunk.bound; node.minH = chunk.minH; node.maxH = chunk.maxH;
    this.ready.add(node);
  }
  #request(node, priority) {
    if (node.state !== 'none') return;
    node.state = 'pending';
    node.ticket = this.pool.request({ type: 'build', planet: this.spec.id, node: { face: node.face, level: node.level, ix: node.ix, iy: node.iy, N: this.N } }, priority, chunk => {
      node.ticket = null;
      if (node.state !== 'pending') return; // cancelled/evicted meanwhile
      this.#attach(node, chunk);
    });
  }
  #release(node) {
    if (node.ticket) { this.pool.cancel(node.ticket); node.ticket = null; }
    if (node.mesh) { this.group.remove(node.mesh); node.mesh.geometry.dispose(); node.mesh = null; }
    node.state = 'none'; this.ready.delete(node); this.shown.delete(node);
    if (node.children) { for (const child of node.children) this.#release(child); node.children = null; }
  }
  /** Re-select the visible chunk set for a camera at `cameraWorld`. */
  update(cameraWorld) {
    this.frame++;
    const cam = this.camLocal.copy(cameraWorld).sub(this.center);
    const next = new Set();
    let pending = 0, occluded = 0;
    const visit = node => {
      node.touched = this.frame;
      if (node.level > 0 && this.#occluded(node, cam)) { occluded++; return; }
      const d = Math.max(0, cam.distanceTo(node.center) - node.bound);
      const wantSplit = node.level < this.maxLevel && d < this.splitK * this.detail * node.arc;
      if (wantSplit) {
        if (!node.children) {
          const L = node.level + 1, x = node.ix * 2, y = node.iy * 2;
          node.children = [this.#node(node.face, L, x, y), this.#node(node.face, L, x + 1, y), this.#node(node.face, L, x, y + 1), this.#node(node.face, L, x + 1, y + 1)];
        }
        let all = true;
        for (const child of node.children) {
          child.touched = this.frame;
          if (this.#occluded(child, cam)) continue; // hidden children need not be ready
          if (child.state !== 'ready') { all = false; if (child.state === 'none') this.#request(child, d + child.level * 4); pending++; }
        }
        if (all) { for (const child of node.children) visit(child); return; }
      }
      next.add(node);
    };
    for (const root of this.roots) visit(root);
    for (const node of this.shown) if (!next.has(node) && node.mesh) node.mesh.visible = false;
    let triangles = 0;
    for (const node of next) { if (!node.mesh) continue; node.mesh.visible = true; triangles += this.N * this.N * 2; }
    this.shown = next;
    // Evict chunks not needed for ~6 s (keeps memory bounded while flying).
    if (this.frame % 30 === 0) {
      for (const node of [...this.ready]) {
        if (node.level === 0) continue;
        if (this.frame - node.touched > 360 && !this.shown.has(node)) this.#release(node);
      }
    }
    this.stats.visible = next.size; this.stats.triangles = triangles; this.stats.pending = pending; this.stats.cached = this.ready.size; this.stats.occluded = occluded;
    return this.stats;
  }
  /** Ground altitude of a world point above the rendered terrain (meters). */
  altitudeAt(worldPoint) {
    const local = worldPoint.clone().sub(this.center), r = local.length(); local.divideScalar(r);
    return r - this.shape.surfaceRadius(local.x, local.y, local.z);
  }
  dispose() { for (const root of this.roots) this.#release(root); this.group.removeFromParent(); }
}
